services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: glasslewis-db
    environment:
      SA_PASSWORD: "HakanBahsi_123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - gl-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5139:5139"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5139
      - ConnectionStrings__SqlConnection=Server=db;Database=GlassLewisDb;User Id=sa;Password=HakanBahsi_123;TrustServerCertificate=True;
    networks:
      - gl-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - gl-network

networks:
  gl-network:
    driver: bridge
